// src/lib/indiaCities.js
export const INDIA_CITIES = [
  { city: "Mumbai", localities: ["Andheri", "Bandra", "Dadar", "Powai", "Vile Parle", "Malad"] },
  { city: "Delhi", localities: ["Connaught Place", "Saket", "Dwarka", "Karol Bagh", "Rohini"] },
  { city: "Bengaluru", localities: ["Indiranagar", "Koramangala", "Whitefield", "Jayanagar", "HSR Layout"] },
  { city: "Hyderabad", localities: ["Banjara Hills", "HiTech City", "Madhapur", "Gachibowli", "Secunderabad"] },
  { city: "Chennai", localities: ["T. Nagar", "Velachery", "Adyar", "Anna Nagar", "OMR"] },
  { city: "Kolkata", localities: ["Salt Lake", "Park Street", "New Town", "Howrah", "Gariahat"] },
  { city: "Pune", localities: ["Kothrud", "Hinjawadi", "Koregaon Park", "Baner", "Viman Nagar"] },
  { city: "Ahmedabad", localities: ["Navrangpura", "Bodakdev", "Maninagar", "SG Highway", "Thaltej"] },
  { city: "Jaipur", localities: ["Malviya Nagar", "Vaishali Nagar", "C-Scheme", "Mansarovar"] },
  { city: "Surat", localities: ["Adajan", "Vesu", "Varachha", "City Light", "Athwa"] },
  { city: "Lucknow", localities: ["Gomti Nagar", "Hazratganj", "Aliganj", "Indira Nagar"] },
  { city: "Indore", localities: ["Vijay Nagar", "Palasia", "Rau", "Bhawarkuan", "Rajendra Nagar"] },
  { city: "Nagpur", localities: ["Dharampeth", "Civil Lines", "Manish Nagar", "Sadar"] },
  { city: "Bhopal", localities: ["Arera Colony", "MP Nagar", "Kolar", "Hoshangabad Road"] },
  { city: "Kanpur", localities: ["Swaroop Nagar", "Kakadeo", "Arya Nagar", "Govind Nagar"] },
  { city: "Thane", localities: ["Ghodbunder", "Vartak Nagar", "Majiwada", "Kalyan"] },
  { city: "Navi Mumbai", localities: ["Vashi", "Nerul", "Kharghar", "Airoli"] },
  { city: "Noida", localities: ["Sector 18", "Sector 62", "Sector 76", "Sector 150"] },
  { city: "Gurugram", localities: ["DLF Phase 1", "Sohna Road", "MG Road", "Golf Course Road"] },
  { city: "Faridabad", localities: ["NIT", "Sector 15", "Badkhal", "Old Faridabad"] },
  { city: "Ghaziabad", localities: ["Indirapuram", "Vaishali", "Raj Nagar", "Kaushambi"] },
  { city: "Chandigarh", localities: ["Sector 17", "Sector 22", "Sector 35", "Manimajra"] },
  { city: "Mohali", localities: ["Phase 3", "Phase 7", "Phase 11", "Kharar"] },
  { city: "Panchkula", localities: ["Sector 8", "Sector 10", "Sector 20", "Mansa Devi"] },
  { city: "Dehradun", localities: ["Rajpur Road", "Race Course", "Ballupur", "Clemn Town"] },
  { city: "Haridwar", localities: ["BHEL", "Ranipur", "Jwalapur", "Kankhal"] },
  { city: "Rishikesh", localities: ["Tapovan", "Muni Ki Reti", "Raiwala"] },
  { city: "Varanasi", localities: ["Bhelupur", "Lanka", "Sigra", "Godowlia"] },
  { city: "Prayagraj", localities: ["Civil Lines", "Katra", "Mumtaz Nagar"] },
  { city: "Patna", localities: ["Kankarbagh", "Boring Road", "Rajendra Nagar", "Patliputra"] },
  { city: "Ranchi", localities: ["Harmu", "Doranda", "Kanke Road", "Lalpur"] },
  { city: "Bhubaneswar", localities: ["Saheed Nagar", "KIIT", "Jaydev Vihar", "Patia"] },
  { city: "Cuttack", localities: ["Badambadi", "Jagatpur", "Choudhury Bazaar"] },
  { city: "Guwahati", localities: ["GS Road", "Beltola", "Dispur", "Maligaon"] },
  { city: "Agra", localities: ["Tajganj", "Sikandra", "Civil Lines", "Dayal Bagh"] },
  { city: "Meerut", localities: ["Shastri Nagar", "Ganga Nagar", "Abu Lane"] },
  { city: "Udaipur", localities: ["Hiran Magri", "Fatehpura", "Old City"] },
  { city: "Jodhpur", localities: ["Ratanada", "Sardarpura", "Pal Road"] },
  { city: "Amritsar", localities: ["Ranjit Avenue", "Lawrence Road", "Majitha Road"] },
  { city: "Ludhiana", localities: ["Civil Lines", "Model Town", "Pakhowal Road"] },
  { city: "Mysuru", localities: ["VV Mohalla", "Gokulam", "Jayalakshmipuram"] },
  { city: "Kochi", localities: ["Kadavanthra", "Panampilly", "Edapally", "Fort Kochi"] },
  { city: "Thiruvananthapuram", localities: ["Kowdiar", "Pattom", "Technopark"] },
  { city: "Coimbatore", localities: ["RS Puram", "Peelamedu", "Saibaba Colony"] },
  { city: "Madurai", localities: ["KK Nagar", "Anna Nagar", "Goripalayam"] },
  { city: "Visakhapatnam", localities: ["MVP Colony", "Dwaraka Nagar", "Seethammadhara"] },
  { city: "Vijayawada", localities: ["Benz Circle", "MG Road", "Poranki"] },
  { city: "Goa", localities: ["Panaji", "Mapusa", "Calangute", "Margao"] },
];
